### ISSUE TITLE
Cloning git repository hangs

### ISSUE THREAD

**Issue by JakeGreer** [matzeeable/wp-reactjs-starter#12]
After running the first two commands `npm install -g create-wp-react-app` and `create-wp-react-app create my-plugin` the initialization on the prjects begins but gets stuck at Clone git repository. The loader just hangs there forever and never passes. Any idea on why this is happening. I made sure that my git email was correct and that I have an ssh key setup. Any help would be appreciated, thanks.

**Comment by matzeeable** [comment]
What OS/CLI are you using? Does it work when you are using `create-wp-react-app` with all the parameters https://github.com/matzeeable/create-wp-react-app#usage ? :-)

**Comment by TKY2048** [comment]
I'm having the same issue. Running it on Windows 10 via CMD.

**Comment by JakeGreer** [comment]
macOS v-10.13.6. I have tried all the parameters and still no luck.

**Comment by unkindee** [comment]
You could try replacing repository = 'git@github.com:matzeeable/wp-reactjs-starter.git', with repository = 'https://github.com/matzeeable/wp-reactjs-starter.git' in the package create.js file, that's what I did.

**Comment by matzeeable** [comment]
Just applied @unkindee suggestion to change the default repository URL (it also was mentioned wrong in the `create-wp-react-app create --help` command). Can you please try if it works now for you? (https://github.com/matzeeable/create-wp-react-app/commit/52978787eabcfec158ead153e114a71dff6aa7f6)

**Comment by JakeGreer** [comment]
Yes that did the trick. Thanks!
